// scripts/extract_lookups.ts — build the id→name lookup tables (COM-41).
//
// Reads the locally-cloned SoH / 2S2H source trees, runs the ported parsers,
// and writes two things from the same parse (so they can't drift):
//   - lookups/<category>_<game>.json  — committed artifact; also what a runtime
//                                        "refresh" re-fetches
//   - src/lookups.data.ts             — the tables the plugin bundles, so it
//                                        resolves names offline with no network
//
// Run:  deno task extract-lookups
// Point it at the clones with SOH_SRC / S2H_SRC env vars; the defaults are the
// local clones under Desktop\SoH Sail\.

import {
  extractEnumBody,
  extractEnumBodyContaining,
  type IdMap,
  parseActorTable,
  parseEnum,
  parseSceneTable,
} from "./parsers.ts";

interface Source {
  game: "soh" | "2s2h";
  category: "items" | "scenes" | "actors" | "flag_types";
  path: string; // relative to the game's source root
  parse: (raw: string) => IdMap;
}

const SOURCES: Source[] = [
  {
    game: "soh",
    category: "items",
    path: "soh/include/z64item.h",
    // SoH's item enum is anonymous — find it by a sentinel member.
    parse: (raw) => {
      const b = extractEnumBodyContaining(raw, "ITEM_BOTTLE");
      return b ? parseEnum(b) : {};
    },
  },
  {
    game: "soh",
    category: "scenes",
    path: "soh/include/tables/scene_table.h",
    parse: parseSceneTable,
  },
  {
    game: "soh",
    category: "actors",
    path: "soh/include/tables/actor_table.h",
    parse: parseActorTable,
  },
  {
    game: "2s2h",
    category: "items",
    path: "mm/include/z64item.h",
    parse: (raw) => {
      const b = extractEnumBody(raw, "ItemId");
      return b ? parseEnum(b) : {};
    },
  },
  {
    game: "2s2h",
    category: "scenes",
    path: "mm/include/tables/scene_table.h",
    parse: parseSceneTable,
  },
  {
    game: "2s2h",
    category: "actors",
    path: "mm/include/tables/actor_table.h",
    parse: parseActorTable,
  },
  {
    game: "2s2h",
    category: "flag_types",
    path: "mm/2s2h/GameInteractor/GameInteractor.h",
    parse: (raw) => {
      const b = extractEnumBody(raw, "FlagType");
      return b ? parseEnum(b) : {};
    },
  },
];

const ROOTS: Record<string, string> = {
  soh: Deno.env.get("SOH_SRC") ??
    "C:/Users/pr3so/Desktop/SoH Sail/SoH-source",
  "2s2h": Deno.env.get("S2H_SRC") ??
    "C:/Users/pr3so/Desktop/SoH Sail/2S2H-gjc-source",
};

type Tables = Record<string, Record<string, Record<string, string>>>;

const data: Tables = {};
const meta: Record<string, { count: number; source: string }> = {};
let failed = 0;

await Deno.mkdir("lookups", { recursive: true });

for (const src of SOURCES) {
  const full = `${ROOTS[src.game]}/${src.path}`;
  try {
    const raw = await Deno.readTextFile(full);
    const entries = src.parse(raw);
    const count = Object.keys(entries).length;
    if (count === 0) {
      console.warn(`! ${src.game}/${src.category}: parsed 0 from ${full}`);
      failed++;
      continue;
    }
    (data[src.game] ??= {})[src.category] = idMapToStringMap(entries);
    meta[`${src.category}_${src.game}`] = { count, source: src.path };

    await Deno.writeTextFile(
      `lookups/${src.category}_${src.game}.json`,
      JSON.stringify(idMapToStringMap(entries), null, 2) + "\n",
    );
    console.log(
      `✓ ${src.game}/${src.category}: ${count} → lookups/${src.category}_${src.game}.json`,
    );
  } catch (err) {
    console.error(
      `✗ ${src.game}/${src.category}: ${
        err instanceof Error ? err.message : String(err)
      } (${full})`,
    );
    failed++;
  }
}

const generatedAt = new Date().toISOString();
const dataModule =
  `// GENERATED by scripts/extract_lookups.ts — do not edit by hand.
// Run \`deno task extract-lookups\` to regenerate from the game source trees.
//
// The plugin bundles these so it resolves ids → names offline, with no network.

export const LOOKUPS_GENERATED_AT = ${JSON.stringify(generatedAt)};

export const LOOKUPS_META: Record<string, { count: number; source: string }> =
  ${JSON.stringify(meta, null, 2)};

export const BUNDLED_LOOKUPS:
  Record<string, Record<string, Record<string, string>>> = ${
    JSON.stringify(data, null, 2)
  };
`;
await Deno.writeTextFile("src/lookups.data.ts", dataModule);
console.log(`\n✓ src/lookups.data.ts written (generated ${generatedAt})`);
console.log(`${SOURCES.length - failed} of ${SOURCES.length} sources ok.`);
if (failed > 0) Deno.exit(1);

/** IdMap has numeric keys; JSON/TS object keys are strings. */
function idMapToStringMap(map: IdMap): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [id, name] of Object.entries(map)) out[id] = name;
  return out;
}
